server:
  port: 8080
spring:
  datasource:
    platform: h2
    url: jdbc:h2:mem:mountain;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL
    #    url: jdbc:h2:tcp://localhost/~/test;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL
    username: sa
    initialize-mode: always
  h2:
    console:
      enabled: true
      path: /h2-console