server:
  port: 8080
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    platform: h2
    url: jdbc:h2:mem:mountain;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL
    #    url: jdbc:h2:tcp://localhost/~/test;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL
    username: sa
    initialize-mode: always
  h2:
    console:
      enabled: true
      path: /h2-console
ribbon:
  eureka:
    enabled: false

feign:
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 3000
        loggerLevel: basic

mountain-client:
  key: '{cipher}d762f3f868f483eafa2af57e9b85e0d47264d4493182f80b1dd903fae4364690c18230ffa6397350bfc891278dc81eb6cdc45cf1f6203383ff2acbae57758a47fd504525ef127dc32d613aedb6812da40fe54f1e0db7e48d07a06398ad96607d7c4e919088b8bfa2f670f97a5aa282e9167dae06d4493d863c1e0d267588eb4b'
  ribbon:
    listOfServers: http://openapi.forest.go.kr

sk-client:
  key: '{cipher}56b651d25e1c1c93ed625749f45633af7babc4097ae3220653ed67dded462c69d796e530f8d18fc8c7a1d101fef369455528eabd1df6e42d9aaf5ba00db6a06b'
  ribbon:
    listOfServers: https://apis.openapi.sk.com
